In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
# 単純なアレイを用意します。
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
# 2つのアレイを列方向（axis=1）に連結します
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
# 行方向（axis=0）に
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# pandas.Seriesでやってみます。
ser1 =  Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])
# concatで、デフォルトは axis=0
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [7]:
# 列方向に連結すると、DataFrameが出来ます。
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [8]:
# 階層的なindexを付けてSeriesを連結することもできます。
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [9]:
# 列方向に連結すると、列の名前になります。
pd.concat([ser1,ser2],axis=1,keys=['cat1','cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [10]:
# DataFrameでも同じ事ができます。
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [11]:
dframe1

X         Y         Z
0 -0.552186 -0.033194 -3.608810
1  0.750265 -1.209736 -1.342089
2 -0.553408  1.742952  0.729737
3  2.401165 -0.413118 -0.706197

In [12]:
dframe2

Y         Q         X
0  0.110080  0.754747 -0.802867
1  0.928928 -0.003529 -0.759998
2  0.059219 -1.032923 -0.785377

In [13]:
# DataFrameを連結します。
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0 -0.552186 -0.033194 -3.608810       NaN
1  0.750265 -1.209736 -1.342089       NaN
2 -0.553408  1.742952  0.729737       NaN
3  2.401165 -0.413118 -0.706197       NaN
0 -0.802867  0.110080       NaN  0.754747
1 -0.759998  0.928928       NaN -0.003529
2 -0.785377  0.059219       NaN -1.032923

In [14]:
# もとのindexを無視することもできます。
pd.concat([dframe1,dframe2],ignore_index=True)

X         Y         Z         Q
0 -0.552186 -0.033194 -3.608810       NaN
1  0.750265 -1.209736 -1.342089       NaN
2 -0.553408  1.742952  0.729737       NaN
3  2.401165 -0.413118 -0.706197       NaN
4 -0.802867  0.110080       NaN  0.754747
5 -0.759998  0.928928       NaN -0.003529
6 -0.785377  0.059219       NaN -1.032923

In [19]:
# We can specify which specific axes to be used
#pd.concat([ser1,ser2],axis=1,join_axes=[['U','V','Y']])
#@ join_axesという引数自体が無くなってしまいました。ここでは、DataFrameから行を選ぶことで代用しています。
pd.concat([ser1,ser2], axis=1).loc[['U','V','Y']]

0    1
U  1.0  NaN
V  2.0  NaN
Y  NaN  4.0

In [19]:
# 公式ドキュメントはこちらです。
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'